#!/bin/bash
# creating builds.json for infra/updater after uploading files or "build-genlog"
SCRIPTNAME=$(basename $BASH_SOURCE)
DEBUG=0

## import vars
source build-config.txt

## temp vars
product_device=(${DEVICES//,/ })
IN=0
ARRAY="RECOVERY,FILESIZE_IMG,SHA256HASH_IMG,FILENAME,FILESIZE,SHA256HASH,BUILD_DATETIME,BUILD_DATE"
array=(${ARRAY//,/ })
NUM=0
LINE=1

## start
rm builds.json
echo { >> builds.json
while [ 1 ]
do
    if [ -z ${product_device[$IN]} ]
    then break
    else
        if [ $LINE = 1 ]
        then echo '"'${product_device[$IN]}'"': [ >> builds.json
        fi
        declare -A ${array[$NUM]}=$(sed -n ''$LINE' p' $TMPDIR/re_${product_device[$IN]}.txt)
        if [ $DEBUG = 1 ]
        then echo ${product_device[$IN]}: NUM: $NUM, LINE: $LINE, array: ${array[$NUM]}: ${!array[$NUM]}  && sleep 0.2
        fi
        if [ $NUM -le 6 ]
        then
            NUM=$(( NUM+1 ))
            LINE=$(( $LINE+1 ))
        else
            IFS='-'
            read -a rom_array <<< "$FILENAME"
            read -a img_array <<< "$RECOVERY"
            unset IFS
            echo  { '"'date'"': '"'$BUILD_DATE'"', '"'datetime'"': $BUILD_DATETIME, '"'filename'"': '"'$FILENAME'"', '"'filepath'"': '"'/$FILENAME'"', \
                    '"'sha256'"': '"'$SHA256HASH'"', '"'size'"': $FILESIZE, '"'type'"': '"'${rom_array[3]}'"', '"'version'"': '"'${rom_array[1]}'"', '"'recovery'"': { \
                    '"'date'"': '"'$BUILD_DATE'"', '"'datetime'"': $BUILD_DATETIME, '"'filename'"': '"'$RECOVERY'"', '"'filepath'"': '"'/$RECOVERY'"', \
                    '"'sha256'"': '"'$SHA256HASH_IMG'"', '"'size'"': $FILESIZE_IMG, '"'type'"': '"'${img_array[3]}'"', '"'version'"': '"'${img_array[1]}'"' \
                  } >> builds.json
            NUM=0
            LINE=$(( $LINE+1 ))
            if [ -z "$(sed -n ''$LINE' p' $TMPDIR/re_${product_device[$IN]}.txt)" ]
            then
                IN=$IN+1
                LINE=1
                if [ -z ${product_device[$IN]} ]
                then echo } ] >> builds.json
                else echo } ], >> builds.json
                fi 
            else
                echo }, >> builds.json
            fi
        fi
    fi
done

## end
echo } >> builds.json
