#!/bin/bash

if [ -z $1 ]
then exit 2
fi

## import vars
source build-config.txt

## setup environment
cd $BUILDDIR
source build/envsetup.sh
export USE_CCACHE=1
export CCACHE_EXEC=/usr/bin/ccache
ccache -M 32G
export CCACHE_COMPRESS=1
export TIMEFORMAT='%3lR'
breakfast $1

## sync repos
if [ -z $2 ]
then
    echo no repo sync, variable not set
else
    if [ $2 = sync ]
    then
        echo syncing repo
        repo sync -c --force-sync --no-clone-bundle --no-tags --no-repo-verify
    else
        echo no repo sync, fix typo: $2
    fi
fi

## begin build process and write duration stats to logfile
echo "begining build process for $1" >> $LOGDIR/$LOG 2>&1
( time brunch $1 ) >> $LOGDIR/$LOG 2>&1

## detect if zip was created, then move to HOME
if [ -e "$OUT"/lineage-*.zip ]
    then
        ## move zip and img
        echo "moving ROM zip and RECOVERY image"
        mv $OUT/lineage-*zip "$ROMDIR/"
        mv $OUT/recovery.img "$ROMDIR/$RECOVERY"
        cp $T/out/build_date.txt "$TMPDIR/build_date_$1.txt"
fi

mka installclean target-files-package otatools

cd $SCRIPTPATH